# Generated by Django 5.1.5 on 2025-01-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_artist',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee')], default='employee', max_length=10),
        ),
    ]
