# Generated by Django 5.1.5 on 2025-02-04 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_user_is_artist_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='requires_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notifications',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.appointment'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='action',
            field=models.CharField(choices=[('created', 'Created Appointment'), ('updated', 'Updated Appointment'), ('canceled', 'Canceled Appointment'), ('pending_approval', 'Pending Approval')], default='pending_approval', max_length=20),
        ),
    ]
