# Generated by Django 5.1.5 on 2025-02-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_appointment_requires_approval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('service_1', 'Service 1'), ('service_2', 'Service 2'), ('service_3', 'Service 3')], default='service_1', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
