# Generated by Django 5.1.5 on 2025-02-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_service_description_alter_service_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='artist',
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('service_1', 'Service 1'), ('service_2', 'Service 2'), ('service_3', 'Service 3')], max_length=100, unique=True),
        ),
    ]
