# Generated by Django 5.1.5 on 2025-02-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_service_artist_alter_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
