# Generated by Django 5.1.5 on 2025-02-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_notifications_approved_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='artist',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='clientprofile',
            old_name='artist',
            new_name='employee',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='confirmed', max_length=10),
        ),
    ]
