# Generated by Django 5.1.5 on 2025-02-19 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_artist_appointment_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(default=datetime.time(12, 0)),
            preserve_default=False,
        ),
    ]
