# Generated by Django 5.1.5 on 2025-02-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_appointment_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='changes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='previous_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='action',
            field=models.CharField(choices=[('created', 'Created Appointment'), ('updated', 'Updated Appointment'), ('canceled', 'Canceled Appointment'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending_approval', max_length=20),
        ),
    ]
